### ISSUE TITLE
[Tech] Create Frontend for the project

### ISSUE THREAD

**Issue by thiago-porto25** [thiago-porto25/search-engine#1]
This task is very complex, therefore I will divide it into small tasks have a reference of them here, and as well in their respective issue.

## Tasks
- [x] Install dependencies.
- [x] Search and add photos to public dir
- [x] Create directory structure.
- [x] Create Routes for frontend.
- [x] Create theme. (dark, light).
- [x] Create Context for theme and for the search
- [x] Create globalStyles
- [x] Create function to request data from API.
- [x] Create pages and their components.
