### ISSUE TITLE
[Tech] Create backend for the project

### ISSUE THREAD

**Issue by thiago-porto25** [thiago-porto25/search-engine#5]
This task is very complex, therefore I will divide it into small tasks have a reference of them here, and as well in their respective issue.

## Tasks
- [x] Install dependencies.
- [x] Set up dependencies.
- [x] Create directory structure.
- [x] Create endpoint.
- [x] Create mock data.
- [x] Create logic to search and serve what matches the title in the request query.
